# Generated by Django 5.1.1 on 2025-11-06 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0009_alter_copon_end_date_alter_copon_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copon',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 6, 17, 15, 44, 781266, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='copon',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 6, 17, 15, 44, 781266, tzinfo=datetime.timezone.utc), verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='discount_basket',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 6, 17, 15, 44, 781660, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='discount_basket',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 6, 17, 15, 44, 781660, tzinfo=datetime.timezone.utc), verbose_name='تاریخ شروع'),
        ),
    ]
