# Generated by Django 5.1.1 on 2025-11-06 17:15

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_name',
            field=models.ImageField(default='', upload_to=utils.FileUpload.upload_to, verbose_name='عکس اصلی'),
        ),
    ]
