# Generated by Django 5.1.1 on 2025-11-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peyment', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peyment',
            old_name='refId',
            new_name='red_id',
        ),
    ]
