# Generated by Django 5.1.1 on 2025-11-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peyment', '0003_rename_refid_peyment_red_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peyment',
            old_name='red_id',
            new_name='refId',
        ),
    ]
