# Generated by Django 5.1.1 on 2025-11-06 17:15

import apps.main.models
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_banner_image_name_alter_infocompany_logo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='infocompany',
            name='logo_name',
            field=models.FileField(upload_to=utils.FileUpload.upload_to, validators=[apps.main.models.validate_image_or_svg]),
        ),
        migrations.AlterField(
            model_name='slider_main',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر'),
        ),
        migrations.AlterField(
            model_name='slider_site',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر'),
        ),
    ]
